zuul:
  retryable: true
  routes:
    user:
      path: /user/**
      url: http://${USER_MSA_URL}/user
    board:
      path: /board/**
      url: http://${BOARD_MSA_URL}/board
    comments:
      path: /comments/**
      url: http://${COMMENT_MSA_URL}/comments

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 32000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 3
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      metrics:
        rollingStats:
          timeInMilliseconds: 10000

user:
  ribbon:
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ConnectTimeout: 3000
    ReadTimeout: 5000
board:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ConnectTimeout: 3000
    ReadTimeout: 5000
comments:
  ribbon:
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ConnectTimeout: 3000
    ReadTimeout: 5000

server:
  port: 28081
    
ApiMasterKey: 'MSA-K-PaaS'
ApiKeySalt: 'K-PaaS'
