apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-msa
  namespace: yang
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: docker.io/mysql:5.6
        name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /docker-entrypoint-initdb.d # 해당 폴더에 .sql 파일 존재 시 Container 생성 시 실행
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret # Secret의 이름
                key: password # Secret의 data에 들어간 key:value
        ports:
        - containerPort: 3306
          name: mysql 
      volumes:
       - name: mysql-persistent-storage
         configMap:
          name: mysql-initdb-config # configMap 설정
       - name: mysql-data
         persistentVolumeClaim:
          claimName: mysql-pv-claim-yang # pv 볼륨 설정
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-msa
  namespace: yang
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30501
  selector:
    app: mysql
