apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-yang # pvc 이름
  namespace: yang
spec:
  storageClassName: cp-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
