apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-msa-config
  namespace: yang
data:
  redis-config: "requirepass password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-msa-ui
  namespace: yang
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis:latest
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-msa-config
            items:
            - key: redis-config
              path: redis.conf
---
apiVersion: v1
kind: Service
metadata:
  name: redis-msa-ui
  namespace: yang
  labels:
    app: redis
spec:
  ports:
  - nodePort: 30801
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: NodePort
